version: '3'
services:
  webapp:
    build:
      context: ./webapp  # Dockerイメージをビルドするコンテキストとしてwebappディレクトリを指定
    volumes:
      - ./webapp:/app
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    tty: true
    # stdin_open: true
    ports:
      - 8000:8000  # 必要に応じてポートを変更
